/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlepvzkelompok7;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class GameLoopTest {
    @Test void testPrint() {
        System.out.println("Gacorrrrrrrrrr");
    }
}
